language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U asyncio aiohttp
  - pip install -U coverage pytest pytest_asyncio pytest_aiohttp pytest-cov
  - pip install -U codecov 
install:
  - pip install -r requirements.txt
script: PYTHONPATH=`pwd` pytest -rpP tests/test_Smile.py --cov=codecov
after_success:
  - codecov # submit coverage
