language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U asyncio aiohttp
  - pip install -U coverage pytest pytest_asyncio pytest_aiohttp
  - pip install codecov
install:
  - pip install -r requirements.txt
script: coverage run --source=. -m pytest -rpP tests/test_Smile.py
after_success:
  - codecov # submit coverage
